"no examples 📝":
  - all: ["packages/eslint-plugin/**/*", "!example-app/**/*"]

"📏 eslint-plugin"
  - all: ["packages/eslint-plugin/**/*","!packages/typescript-config/**/*"]

"typescript-config"
  - all: ["packages/typescript-config/**/*","!packages/eslint-plugin/**/*"]