name: "PR Conventional Title Checker"
on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-title:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: thehanimo/pr-title-checker@v1.4.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pass_on_octokit_error: false
          configuration_path: .github/pr-conventional-title-checker-config.json
