name: Publish Packages
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Bootstrap Lerna
        run: npx lerna bootstrap

      - name: Publish packages
        run: npx lerna publish from-package --no-private
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
