name: Publish to npm

on:
  push:
    tags:
      - "**"

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm-publish
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          registry-url: "https://registry.npmjs.org"

      - name: Upgrade npm for trusted publishing
        run: npm install -g npm@latest

      - name: Install dependencies
        run: yarn --immutable

      - name: Build eslint-plugin
        run: yarn workspace @bam.tech/eslint-plugin build

      - name: Publish to npm
        run: npx lerna publish from-package --no-private --yes
