name: Publish to npm

on: pull_request

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: "chore/npm-publish-auto" # Replace with your branch name

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn --immutable
        # run: npm ci

      #   - name: Bootstrap Lerna
      #     run: npx lerna bootstrap

      - name: Set up .npmrc file
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish to npm
        run: npx lerna publish from-package --no-private --yes --loglevel "verbose"
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
